### ISSUE TITLE
Protocol VS Integration pattern

### ISSUE THREAD

**Issue by spakendralo** [mauvaisetroupe/ea-design-it#46]
A proposal. Looking at the documentation, the "protocol" should perhaps be called "integration pattern". The reason is that some integration patterns are made out of several protocols. There may be technical components that are not EA applications that are involved and create protocol adaptations.

Sometime later, in the tool or outside of it in some Wiki pages, one will want to have the Integration Pattern explained and will show what are the technical components that create it and what are associated protocols.

**Comment by mauvaisetroupe** [comment]
> The reason is that some integration patterns are made out of several protocols.

Could you pleas give an example? 

I understand that you talk about something like ESB protocol :
 - (APPLICATION_1)  --ESB-->  (APPLICATION_2)
 - that in physically implemented by (APPLICATION_1)  --MQ--> --ESB--> --MQ-->  (APPLICATION_2)

Is it Correct? Something else in your mind?

**Comment by mauvaisetroupe** [comment]
I understand your point. You have a very "physical" definition of protocol.
I guess when I start using this word in the present context I had a more conceptual definition

From wikipedia

> A communication protocol is a system of rules that allows two or more entities of a communications system to transmit information via any kind of variation of a physical quantity. The protocol defines the rules, syntax, semantics and synchronization of communication and possible error recovery methods. Protocols may be implemented by hardware, software, or a combination of both.

I have a conceptual interpretation of this definition (that I admit doesn't really fit with the rest of wikipedia post) 
Do you think we have a different definition of a protocol? What is yours?

**Comment by spakendralo** [comment]
I think we have the same definition. Protocol is a description of how the interaction needs to happen, but does not say **how this is implemented** - and this is precisely what interests me, the implementation framework. I am not interested if the protocol is "FILE", I want to know where to look for the file transfer definition. 

I will express this as a requirement so you see the need: 
As a person who maintains the architectural landscape, I need to map discovered flows with the defined ones. E.g.: I will have some routes and validation schemas extracted from an MFT software, and I want to know where to map this. In the reverse order, if I look at an Interface, I would like to understand where to find the definition for it.

**Comment by mauvaisetroupe** [comment]
In conclusion,  Protocol entity match your needs. Actually a Protocol has a name and a type. For a type "File" you can have many Protocols like "Sftp file" , "iMFT batch file", etc. that match your integration pattern concept. I propose to close the issue for now

**Comment by spakendralo** [comment]
Closing as agreed.
